test_name: Tags

stages:
  - name: Add an article with a new tag
    request:
      url: "http://localhost/article/1/tags/HiAvery"
      method: PUT
      headers:
        content-type: application/json
    response:
      status_code: 201

  - name: List all articles with the new tag
    request:
      url: "http://localhost/article/tags/HiAvery"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200

  - name: Add another tag to the article
    request:
      url: "http://localhost/article/1/tags/ILikeTurrtles"
      method: PUT
      headers:
        content-type: application/json
    response:
      status_code: 201

  - name: Delete one of the tags from the article
    request:
      url: "http://localhost/article/1/tags/HiAvery"
      method: DELETE
      headers:
        content-type: application/json
    response:
      status_code: 200

  - name: Add a tag to an article that doesn't exist
    request:
      url: "http://localhost/article/1/tags/HiAvery2"
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 404
