test_name: Articles

stages:
  - name: Try to post an article without authenticating
    request:
      url: "http://localhost/articles"
      method: POST
      headers:
        content-type: application/json
      json:
        title: "Getting into The Avengers"
        body: "All you need is to get Thano's gauntlet."
        username: "StarLord"
    response:
      status_code: 404

  - name: Try a post an article using the wrong password
    request:
      url: "http://localhost/articles"
      method: POST
      headers:
        content-type: application/json
      json:
        title: "Getting into The Guardians"
        body: "There are many ways to get accepted into the Guardians"
        username: "StarLord1"
        password: "ilovegamora1"
    response:
      status_code: 401

  - name: Post an article successfully
    request:
      url: "http://localhost/articles"
      method: POST
      headers:
        content-type: application/json
      json:
        title: "Getting into The Guardians"
        body: "There are many ways to get accepted into the Guardians"
        username: "StarLord1"
    response:
      status_code: 201

  - name: Retrieve the newly posted article
    request:
      url: "http://localhost/articles/1"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200

  - name: Check that the newly posted articles is the most recent
    request:
      url: "http://localhost/articles/recent/1"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200
