test_name: Users

stages:
  - name: Try to change the password for a user that does not exist
    request:
      url: "http://localhost/users"
      method: PATCH
      headers:
        content-type: application/json
      json:
        user: "test"
        password: "data"
    response:
      status_code: 404

  - name: Create a user
    request:
      url: "http://localhost/register"
      method: POST
      headers:
        content-type: application/json
      json:
          username: "StarLord1"
          email: "iamstarloard@marvel.com"
          password: "ilikemusic1"
    response:
      status_code: 201

  - name: Change a user's password
    request:
      url: "http://localhost/users"
      method: PATCH
      headers:
        content-type: application/json
      json:
        user: "StarLord1"
        new_pass: "iamgroot1"
    response:
      status_code: 200

  - name: Delete the user
    request:
      url: "http://localhost/users"
      method: DELETE
      headers:
        content-type: application/json
      json:
        username: "StarLord1"
    response:
      status_code: 200

  - name: Try to change the password for the deleted user
    request:
      url: "http://localhost/users"
      method: PATCH
      headers:
        content-type: application/json
      json:
        user: "StarLord1"
        new_pass: "thanos6stones"
    response:
      status_code: 404
